config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get 'attend_employees'
      get 'attendances/one_month_apply'
      patch 'attendances/update_one_month_apply'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    collection do
      post 'import'
      resources :offices
    end
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :affiliation, length: { in: 2..30 }, allow_blank: true
  validates :basic_work_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search)
    return User.all unless search
    User.where(['name LIKE ?', "%#{search}%"])
  end
  
  def self.import(file)
    imported_num = 0
    
    open(file.path, 'r:cp932:utf-8', undef: :replace) do |f|
      csv = CSV.new(f, :headers => :first_row)
      csv.each do |row|
        next if row.header_row?
        table = Hash[[row.headers, row.fields].transpose]
        
        user = find_by(email: table["email"])
        if user.nil?
          user = new
        end
        
        user.attributes = table.to_hash.slice(*table.to_hash.except(:email, :created_at, :updated_at).keys)
        
        if user.valid?
          user.save!
          imported_num += 1
        end
      end
    end
    imported_num
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy attend_employees edit_basic_info update_basic_info)
  before_action :logged_in_user, only: %i(index show edit update destroy attend_employees edit_basic_info update_basic_info)
  # before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: %i(index destroy attend_employees edit_basic_info update_basic_info)
  before_action :admin_or_correct_user, only: %i(show)
  before_action :set_one_month, only: %i(show attend_employees)
  # before_action :set_one_month_apply, only: %i(one_month_apply)
  
  def index
    if params[:search] == ""
      redirect_to users_url
      flash[:danger] = "キーワードを入力してください。"
    else
      @users = User.paginate(page: params[:page]).search(params[:search]).order(id: "ASC")
      if params[:search].present?
        flash.now[:success] = "検索結果:#{@users.count}件"
      end
    end
  end
  
  def import
    if params[:csv_file].blank?
      flash[:danger] = "インポートするCSVファイルを選択してください。"
      redirect_to users_url
    else
      num = User.import(params[:csv_file])
      flash[:success] = "#{num.to_s}件のユーザー情報を追加/更新しました。"
      redirect_to users_url
    end
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザーの新規登録に成功しました。"
      redirect_to @user
    else
      render :new
    end
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
    @users = when_superior
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "#{@user.name}の情報を更新しました。"
      redirect_to users_url
    elsif @user.name.blank?
      flash[:danger] = "更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
      redirect_to users_url
    else
      flash[:danger] = "#{@user.name}の更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
      redirect_to users_url
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def attend_employees
    @users = working_users
  end
  
  # def one_month_apply
  #   @users = User.all
  #   @attendance = Attendance.find(params[:id])
  # end
  
  # def update_one_month_apply
  #   if @user.update_attributes(month_apply_params)
  #     flash[:success] = "#{@user.name}の申請を提出しました。"
  #     redirect_to user_url
  #   else
  #     flash[:danger] = "#{@user.name}の申請に失敗しました。"
  #     redirect_to user_url
  #   end
  # end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :superior, :admin, :password, :password_confirmation)
    end
    
    def basic_info_params
      params.require(:user).permit(:affiliation, :basic_work_time, :work_time)
    end
    
    # def month_apply_params
    #   params.require(:user).permit(attendances: [:superior_id, :month_apply, :month_approval])[:attendances]
    # end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
  
  def when_superior
    User.where(superior: true)
  end
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info' ) %>
<% provide(:btn_text, '更新' ) %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1>基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>
            
            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>
            
            <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :affiliation, class: "form-control" %>
            
            <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_work_time, class: "form-control" %>
            
            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>
            
            <div class="center">
              <%= f.submit yield(:btn_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: user %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>
  
  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>
  
  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/attend_employees.html.erb
<% provide(:title, "出勤社員一覧") %>
<h1>出勤社員一覧</h1>

<% if @users.count == 0 %>
  <h1>現在出社している社員はいません。</h1>
<% else %>
  <table class="table table-condensed table-bordered table-hover" id="attend-table">
    <thead>
      <tr>
        <td>社員番号</td>
        <td>名前</td>
      </tr>
    </thead>
    <tbody>
      <% @users.zip(@attendances) do |user, day| %>
        <tr>
          <td><%= user.employee_number %></td>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "ユーザー情報編集") %>
<% provide(:class_text, "user--edit") %>
<% provide(:btn_text, "更新") %>
<h1>ユーザー情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit_basic_info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit_basic_info").modal("show");

app/views/users/index.html.erb
<% provide(:title, "ユーザー一覧") %>
<% provide(:class_text, "user--edit") %>
<% provide(:btn_text, "更新") %>
<h1><%= params[:search].present? ? "検索結果" : "ユーザー一覧" %></h1>
<h3 class="center"><%= link_to "戻る", users_path if params[:search].present? %></h3>

<div class="container">
  <div class="row form-group">
    
    <!-- CSVインポートフォーム -->
    <div class="col-md-4 col-md-offset-1 csv-group">
      <%= form_tag(import_users_path, method: :post, multipart: true) do %>
        <%= file_field_tag :csv_file, class: "form-control form-csv" %>
        <%= submit_tag "CSVをインポート", class: "btn btn-primary btn-block btn-csv" %>
      <% end %>
    </div>
    
    <!-- ユーザー検索フォーム -->
    <div class="col-md-2 col-md-offset-2 input-group">
      <p>ユーザー名検索</p>
      <%= form_tag(users_path, method: :get) do %>
        <span class="input-group-btn">
          <%= text_field_tag :search, '', placeholder: 'キーワドを入力', class: "form-control"  %>
          <%= submit_tag '検索', name: :nil, class: "btn btn-primary" %>
        </span>
      <% end %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-10 col-md-offset-1 paginate-top"><%= will_paginate %></div>
  </div>
  
  <div class="row col-md-10 col-md-offset-1 acd-users">
    <% @users.each do |user| %>
      <div>
        <div>
          <p><%= user.name %></p>
          <p>| <%= link_to "削除", '#', class: "btn btn-primary" %></p>
        </div>
        
        <!-- アコーディオン表示 -->
        <div class="acd jumbotron">
          <div class="acd-content col-md-2">
            <a class="btn btn-primary btn-lg btn-edit" data-toggle="collapse" href="#collapse<%= user.id %>" role="button"> <!-- user.idを渡して各ユーザーに紐付け -->
              編集
            </a>
          </div>
        </div>
        <div class="collapse collapse-panel" id="collapse<%= user.id %>"> <!-- user.idを渡して各ユーザーに紐付け -->
          <div class="collapse-body">
            <%= render 'form', { user: user } %> <!-- render partial: 'form', locals: { user: user } でも可。 -->
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
  <div class="row">
    <div class="col-md-10 col-md-offset-1 paginate-bottom"><%= will_paginate %></div>
  </div>
</div>



 


<!-- ここから保留 -->
<div class="col-md-10 col-md-offset-1">
  <div class="input-group">
    <p>ユーザー名検索</p>
    <%= form_tag(users_path, method: :get) do %>
      <span class="input-group-btn">
        <%= text_field_tag :search, '', placeholder: 'キーワドを入力', class: "form-control"  %>
        <%= submit_tag '検索', name: :nil, class: "btn btn-primary" %>
      </span>
    <% end %>
  </div>
  <div class="paginate-top"><%= will_paginate %></div>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
      </tr>
    </thead>
    
    <% @users.each do |user| %>
      <tr>
        <td><%= current_user.admin? ? (link_to user.name, user) : user.name %></td>
        <td>
          <%= link_to "基本情報編集", edit_basic_info_user_path(user), remote: true, class: "btn btn-success" if current_user.admin? %>
          <%= link_to "削除", user, method: :delete,
              data: { confirm: "#{user.name}のデータを削除しますか？" },
              class: "btn btn-danger" if current_user.admin? && !current_user?(user) %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>
<!-- ここまで保留 -->

<!-- モーダルウィドウ -->
<div id="edit_basic_info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_basic_info" data-toggle="collapse" href="edit_basic_info" role="button" aria-expanded="false" aria-controls="edit_basic_info"></div>

app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<% provide(:class_text, "signup") %>
<% provide(:btn_text, "新規作成") %>

<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      
      <%= f.label :name, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :email, class: "label-#{yield(:class_text)}" %>
      <%= f.email_field :email, class: "form-control" %>
      
      <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :affiliation, class: "form-control" %>
      
      <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
      <%= f.number_field :employee_number, class: "form-control" %>
      
      <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
      <%= f.text_field :uid, class: "form-control" %>
      
      <%= f.label :password, class: "label-#{yield(:class_text)}" %>
      <%= f.password_field :password, class: "form-control" %>
      
      <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      
      <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_work_time, class: "form-control" %>
      
      <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :designated_work_start_time, class: "form-control" %>
      
      <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :designated_work_end_time, class: "form-control" %>
      
      <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div>
  <table class="table table-bordered table-condensed" id="user-table">
    <thead>
      <tr>
        <td>
          <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
          &emsp;<%= l(@first_day, format: :middle) %>&emsp;時間管理表&emsp;
          <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
        </td>
        <td>
          指定勤務開始時間&emsp;<%= @user.designated_work_start_time.strftime("%R") %><br>
          指定勤務終了時間&emsp;<%= @user.designated_work_end_time.strftime("%R") %>
        </td>
        <td colspan="3">基本時間&emsp;<%= format_basic_info(@user.basic_work_time) %></td>
        <td>初月&emsp;<%= @first_day.strftime('%m/%d') %></td>
      </tr>
      <tr>
        <td>所属&emsp;<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
        <td>氏名&emsp;<%= @user.name %></td>
        <td>コード</td>
        <td><%= @user.employee_number %></td>
        <td>出勤日数&emsp;<%= @worked_sum %>日</td>
        <td>締め&emsp;<%= @last_day.strftime('%m/%d') %></td>
      </tr>
    </thead>
  </table>
  
  <% if current_user.superior? %>
    <div class="news">
      <p>🔺【所属長承認申請のお知らせ】<%= link_to "XX件の通知があります。", attendances_one_month_apply_user_path(current_user), class: "notice-superior" %></p>
      <p>❌【勤怠変更申請のお知らせ】</p>
      <p>❌【残業申請のお知らせ】</p>
    </div>
  <% end %>
  
  <div class="btn-user-table">
    <div class="btn-proup">
      <%= link_to "勤怠情報を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
      <%= link_to "❌CSV出力", '#', class: "btn btn-primary" %>
      <%= link_to "❌勤怠編集ログ(承認済)", '#', class: "btn btn-primary" %>
    </div>
  </div>
  
  <table class="table table-bordered table-condensed table-striped" id="user-table">
    <thead>
      <tr>
        <td rowspan="4">残業申請</td>
        <td rowspan="4">日付</td>
        <td rowspan="4">曜日</td>
      </tr>
      <tr>
        <td colspan="8">【実績】</td>
        <td colspan="5">所定外勤務</td>
      </tr>
      <tr>
        <td colspan="3">出社</td>
        <td colspan="3">退社</td>
        <td rowspan="2">在社時間</td>
        <td rowspan="2">備考</td>
        <td colspan="2">終了時間</td>
        <td rowspan="2">時間外時間</td>
        <td rowspan="2">業務処理内容</td>
        <td rowspan="2">指示者確認</td>
      </tr>
      <tr>
        <td>時</td>
        <td>分</td>
        <td></td>
        <td>時</td>
        <td>分</td>
        <td></td>
        <td>時</td>
        <td>分</td>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= link_to "❌残業申請", '#', class: "btn btn-primary" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td>
            <% if day.worked_on.wday == 0 %>
              <font color="#ff000">
            <% elsif day.worked_on.wday == 6 %>
              <font color="#0033cc">
            <% end %>
            <%= $days_of_the_week[day.worked_on.wday] %>
          </td>
          <td><%= day.started_at.hour if day.started_at.present? %></td>
          <td><%= day.started_at.floor_to(15.minutes).strftime("%M") if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_attend(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-block btn-attendance" %>
            <% end %>
          </td>
          <td><%= day.finished_at.hour if day.finished_at.present? %></td>
          <td><%= day.finished_at.floor_to(15.minutes).strftime("%M") if day.finished_at.present? %></td>
          <td>
            <% if btn_text = attendance_leave(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-block btn-attendance" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <tr>
        <td></td>
        <td colspan="2"></td>
        <td colspan="6"></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="5"></td>
        <td>
          <div class="application-form">
            <%= "❌所属長承認\u329e　未" %>
            <%= form_with(model: @attendances, url: attendances_update_one_month_apply_user_path(@first_day, current_user), method: :patch, local: true) do |f| %>
            <%= f.select :user, @users.pluck(:name, :id), {include_blank: true}, {class: "form-control"} %>
            <div>
            <%= f.submit "申請", class: "btn btn-primary btn-block" %>
            </div>
            <% end %>
          </div>
        </td>
      </tr>
    </tfoot>
  </table>
</div>