config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users do
    member do
      get 'attend_employees'
      get 'attendances/one_month_apply'
      patch 'attendances/update_one_month_apply'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    collection do
      post 'import'
      resources :offices
    end
    resources :attendances, only: :update
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  
  validate :finished_at_is_invalid_without_a_started_at
  validate :started_at_than_finished_at_fast_if_invalid
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です。") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
     errors.add(:started_at, "より早い退社時間は無効です。") if started_at > finished_at
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: %i(edit_one_month update_one_month one_month_apply update_one_month_apply)
  before_action :logged_in_user, only: %i(update edit_one_month update_one_month one_month_apply)
  before_action :admin_or_correct_user, only: %i(edit_one_month update_one_month)
  before_action :set_one_month, only: %i(edit_one_month)
  before_action :set_one_month_apply, only: %i(one_month_apply)
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  def edit_one_month
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do
      if attendances_invalid?
        attendances_params.each do |id, item|
          attendance = Attendance.find(id)
          attendance.update_attributes!(item)
        end
        flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
        redirect_to user_url(date: params[:date])
      else
        flash[:danger] = "不正な時間入力がありました、再入力してください。"
        redirect_to attendances_edit_one_month_user_url(date: params[:date])
      end
    end
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  def one_month_apply
    @users = User.all
    @attendance = Attendance.find(params[:id])
  end
  
  def update_one_month_apply
    if @attendance.update_attributes(month_apply_params)
      flash[:success] = "#{@user.name}の申請を提出しました。"
      redirect_to user_url
    else
      flash[:danger] = "#{@user.name}の申請に失敗しました。"
      redirect_to user_url
    end
  end
  
  private
  
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
    
    def month_apply_params
      params.require(:user).permit(attendances: [:superior_id, :status, :month_apply, :month_approval, :month_check])[:attendances]
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_attend(attendance)
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
    end
    false
  end
  
  def attendance_leave(attendance)
    if Date.current == attendance.worked_on
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    false
  end
  
  # 本日の勤務中社員取得用
  def working_users
    User.where(id: Attendance.where.not(started_at: nil).
         where(id: Attendance.where(finished_at: nil)).
         where(id: Attendance.where(worked_on: Date.current)).select(:user_id))
  end
  
  def attendances_invalid?
    attendances = true
    attendances_params.each do |id, item|
      if item[:started_at].blank? && item[:finished_at].blank?
        next
      elsif item[:started_at].blank? || item[:finished_at].blank?
        attendances = false
        break
      elsif item[:started_at] > item[:finished_at]
        attendances = false
        break
      end
    end
    return attendances
  end
  
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
end

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
<div>
  <h1>勤怠編集</h1>
  <table class="table table-bordered table-condensed table-striped table-hover" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出社</th>
        <th>退社</th>
        <th>翌日</th>
        <th>在社時間</th>
        <th>備考</th>
        <th>指示者確認&#x329E;</th>
      </tr>
    </thead>
    <tbody>
      <% @attendances.each do |day| %>
        <%= f.fields_for "attendances[]", day do |attendance| %>
          <tr>
            <td><%= l(day.worked_on, format: :short) %></td>
            <td>
              <% if day.worked_on.wday == 0 %>
                <font color="#ff000">
              <% elsif day.worked_on.wday == 6 %>
                <font color="#0033cc">
              <% end %>
              <%= $days_of_the_week[day.worked_on.wday] %>
            </td>
            <% if Date.current < day.worked_on %>
              <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
              <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
            <% else %>
              <td><%= attendance.time_field :started_at, class: "form-control" %></td>
              <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
            <% end %>
            <td></td>
            <td>
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= working_times(day.started_at, day.finished_at) %>
              <% end %>
            </td>
            <td><%= attendance.text_field :note, class: "form-control" %></td>
            <td></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
  </div>
</div>
<% end %>

app/views/attendances/one_month_apply.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <div class="row">
      <% @users.each do |user|%>
        <% if @attendance.month_check == "0" %>
          <div class="col-md-12">
            <h3>【<%= user.name %>からの1ヶ月分の勤怠申請 <%= user.superior %>】</h3>
            <table class="table table-condensed table-bordered table-hover">
              <thead>
                <tr>
                  <th class="center">月</th>
                  <th class="center">指示者確認<%= "\u329e" %></th>
                  <th class="center">変更</th>
                  <th class="center">勤怠を確認する</th>
                </tr>
              </thead>
              <% @attendances.each do |month|%>
                <%= fields_for "attendances[]", month do |attendance| %>
                  <tbody>
                    <tr>
                      <td><%= month.worked_on %></td>
                      <td>
                        <div class="application-form">
                         <div class="form-group">
                           <select class="form-control" id="application" name="application">
                             <option></option>
                             <option></option>
                           </select>
                         </div>
                        </div>
                      </td>
                      <td class="center"><%= check_box_tag :sample %></td>
                      <td class="center"><%= link_to "確認", '#', class: "btn btn-lg btn-primary" %></td>
                    </tr>
                  </tbody>
                <% end %>
              <% end %>
            </table>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-md-4 col-md-offset-4">
    <%= link_to "変更を送信する", '#', class: "btn btn-lg btn-primary btn-block" %>
  </div>
</div>